version: "3.9"

services:
  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./global-config/db-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - coredef-network

  control-center:
    build:
      context: ./control-center
    ports:
      - "5000:5000"
    volumes:
      - ./global-config:/config:ro
    environment:
      CONFIG_PATH: /config/config.json
    depends_on:
      - db
    networks:
      - coredef-network

  vulnerability-scanner:
    build:
      context: ./vulnerability-scanner
    volumes:
      - ./global-config:/config:ro
    environment:
      CONFIG_PATH: /config/config.json
    depends_on:
      - db
    networks:
      - coredef-network

  decoy-system:
    build:
      context: ./decoy-system
    ports:
      - "80:80"
      - "445:445"
    volumes:
      - ./global-config:/config:ro
      - ./decoy-system/public:/app/public  # SMB share
    environment:
      CONFIG_PATH: /config/config.json
    depends_on:
      - db
    networks:
      - coredef-network

volumes:
  db_data:

networks:
  coredef-network:
    driver: bridge
